server:
    host: localhost
    mode: debug
    port: 8090
    online: true #true表示hf-mirror找不到，去hfNetLoc地址查找并下载模型数据，false表示本地如果没有，直接返回没有
    repos: ./repos
    hfNetLoc: hf-mirror.com   # huggingface.co     hf-mirror.com
    hfScheme: https
    hfLfsNetLoc : cdn-lfs.huggingface.co

download:
    blockSize: 8388608           #默认文件块大小为8MB（8388608），单位字节，1048576（1MB）
    reqTimeout: 0                #远端请求超时时间，单位秒，默认为0，不超时。
    respChunkSize: 8192          #默认对响应结果的读取大小8192，单位字节。
    remoteFileRangeSize: 0    #按照这个长度分块下载，0为不切分,测试选项：8388608（8M），67108864（64M），134217728（128M）,536870912(512M),1GB（1073741824）
    remoteFileRangeWaitTime: 1   #每个分区文件下载任务提交时间间隔，默认1s，单位（s）。
    goroutineMaxNumPerFile: 8    #远程下载任务启动的最大协程数量
    remoteFileBufferSize: 67108864  #每个分区文件的结果缓存大小
    prefetchBlocks: 16           #预先读取块的数量

retry:
    delay: 1       #重试间隔时间，单位秒，默认为1
    attempts: 3    #重试次数，默认为3

log:
    maxSize: 1      # 日志文件最大的尺寸（MB）
    maxBackups: 10  #保留旧文件的最大个数
    maxAge: 90      #保留旧文件的最大天数